micronaut:
  application:
    name: mafirst
  server:
    port: 9090

application:
  max: 100

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    schema-generate: CREATE_DROP
    dialect: H2


jpa:
  default:
    entity-scan:
      packages:
        - 'com.example.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

